language: python
python:
  - "3.3"
  - "3.4"
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - make test
notifications:
  slack: ticketplace:X20IHgm20jEoqNslOHUcuGsf