language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - make test
notifications:
  slack: ticketplace:X20IHgm20jEoqNslOHUcuGsf