"""empty message

Revision ID: 1562d1f3e9
Revises: 93c6695f7f
Create Date: 2015-12-23 13:05:46.282828

"""

# revision identifiers, used by Alembic.
revision = '1562d1f3e9'
down_revision = '93c6695f7f'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    ### end Alembic commands ###
