"""empty message

Revision ID: 160265344b6
Revises: 46dc9749ab9
Create Date: 2016-01-08 12:24:55.055573

"""

# revision identifiers, used by Alembic.
revision = '160265344b6'
down_revision = '46dc9749ab9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'bus_parking_info', new_column_name='info_bus_parking')
    op.alter_column('content', 'information1', new_column_name='info_eduticket')
    op.alter_column('content', 'information2', new_column_name='info_details')
    op.alter_column('content', 'information4', new_column_name='info_time')
    op.alter_column('content', 'information5', new_column_name='info_refund')
    op.alter_column('content', 'seating_arrangement', new_column_name='info_seat')
    op.alter_column('content', 'transportation_info', new_column_name='info_transportation')
    op.alter_column('content', 'age_min', new_column_name='mininum_age')
    op.add_column('company', sa.Column('postcode', sa.Text(), nullable=True))
    op.drop_column('company', 'postcode2')
    op.drop_column('company', 'postcode1')
    op.add_column('content', sa.Column('theater_postcode', sa.Text(), nullable=True))
    op.drop_column('content', 'theater_postcode1')
    op.drop_column('content', 'theater_postcode2')
    op.drop_column('content', 'longitude')
    op.drop_column('content', 'account_number')
    op.drop_column('content', 'resolved_money')
    op.drop_column('content', 'information3')
    op.drop_column('content', 'age_max')
    op.drop_column('content', 'modified_date')
    op.drop_column('content', 'account_name')
    op.drop_column('content', 'account_bank_code')
    op.drop_column('content', 'resolved_note')
    op.drop_column('content', 'landing_ad')
    op.drop_column('content', 'latitude')
    op.drop_column('content', 'information_file')
    ### end Alembic commands ###


def downgrade():
    op.alter_column('content', 'info_bus_parking', new_column_name='bus_parking_info')
    op.alter_column('content', 'info_eduticket', new_column_name='information1')
    op.alter_column('content', 'info_details', new_column_name='information2')
    op.alter_column('content', 'info_time', new_column_name='information4')
    op.alter_column('content', 'info_refund', new_column_name='information5')
    op.alter_column('content', 'info_seat', new_column_name='seating_arrangement')
    op.alter_column('content', 'info_transportation', new_column_name='transportation_info')
    op.alter_column('content', 'mininum_age', new_column_name='age_min')
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('information_file', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('information3', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('age_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('landing_ad', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('content', sa.Column('resolved_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('account_bank_code', sa.TEXT(), autoincrement=False, nullable=False, server_default=''))
    op.add_column('content', sa.Column('account_name', sa.TEXT(), autoincrement=False, nullable=False, server_default=''))
    op.add_column('content', sa.Column('modified_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('resolved_money', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('account_number', sa.TEXT(), autoincrement=False, nullable=False, server_default=''))
    op.add_column('content', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('theater_postcode1', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('content', sa.Column('theater_postcode2', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.drop_column('content', 'theater_postcode')
    op.add_column('company', sa.Column('postcode1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('postcode2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('company', 'postcode')
    ### end Alembic commands ###
