"""empty message

Revision ID: 195d5fc0228
Revises: 160265344b6
Create Date: 2016-01-08 12:42:46.498856

"""

# revision identifiers, used by Alembic.
revision = '195d5fc0228'
down_revision = '160265344b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'actor_change',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'info_bus_parking',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'info_seat',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'info_transportation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'inquire_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'invitation_ticket_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'manager_email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'manager_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'manager_phone',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'mininum_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'teacher_ticket_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'theater_address1',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'theater_address2',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'theater_name',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'theater_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'theater_address2',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'theater_address1',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'teacher_ticket_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content', 'mininum_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content', 'manager_phone',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'manager_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'manager_email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'invitation_ticket_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'inquire_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'info_transportation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'info_seat',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'info_bus_parking',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content', 'actor_change',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
